# **Final Project Task 1 - Census Data Preprocess**

Requirements

- Target variable specification:
    - The target variable for this project is hours-per-week. 
    - Ensure all preprocessing steps are designed to support regression analysis on this target variable.
- Encode data  **3p**
- Handle missing values if any **1p**
- Correct errors, inconsistencies, remove duplicates if any **1p**
- Outlier detection and treatment if any **1p**
- Normalization / Standardization if necesarry **1p**
- Feature engineering **3p**
- Train test split, save it.
- Others?


Deliverable:

- Notebook code with no errors.
- Preprocessed data as csv.

In [1]:
import pandas as pd

In [2]:
data_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
columns = [
    "age", "workclass", "fnlwgt", "education", "education-num", "marital-status",
    "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss",
    "hours-per-week", "native-country", "income"
]

data = pd.read_csv(data_url, header=None, names=columns, na_values=" ?", skipinitialspace=True)
data.head()

data.to_csv("adult_data", index=False)
adult_data = data

In [3]:
adult_data.head()

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country income  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

In [4]:
adult_data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [5]:
print("Dimensiune dataframe:", adult_data.shape)
print("\nTipuri de date:")
print(adult_data.dtypes)

Dimensiune dataframe: (32561, 15)

Tipuri de date:
age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
income            object
dtype: object


In [6]:
adult_data["sex"].value_counts()


sex
Male      21790
Female    10771
Name: count, dtype: int64

In [7]:
print("\nProcent lipsuri pe coloană (%):")
print((adult_data.isna().mean() * 100).round(2))


Procent lipsuri pe coloană (%):
age               0.0
workclass         0.0
fnlwgt            0.0
education         0.0
education-num     0.0
marital-status    0.0
occupation        0.0
relationship      0.0
race              0.0
sex               0.0
capital-gain      0.0
capital-loss      0.0
hours-per-week    0.0
native-country    0.0
income            0.0
dtype: float64


In [8]:
for col in adult_data:
    print(adult_data[col].unique())

[39 50 38 53 28 37 49 52 31 42 30 23 32 40 34 25 43 54 35 59 56 19 20 45
 22 48 21 24 57 44 41 29 18 47 46 36 79 27 67 33 76 17 55 61 70 64 71 68
 66 51 58 26 60 90 75 65 77 62 63 80 72 74 69 73 81 78 88 82 83 84 85 86
 87]
['State-gov' 'Self-emp-not-inc' 'Private' 'Federal-gov' 'Local-gov' '?'
 'Self-emp-inc' 'Without-pay' 'Never-worked']
[ 77516  83311 215646 ...  34066  84661 257302]
['Bachelors' 'HS-grad' '11th' 'Masters' '9th' 'Some-college' 'Assoc-acdm'
 'Assoc-voc' '7th-8th' 'Doctorate' 'Prof-school' '5th-6th' '10th'
 '1st-4th' 'Preschool' '12th']
[13  9  7 14  5 10 12 11  4 16 15  3  6  2  1  8]
['Never-married' 'Married-civ-spouse' 'Divorced' 'Married-spouse-absent'
 'Separated' 'Married-AF-spouse' 'Widowed']
['Adm-clerical' 'Exec-managerial' 'Handlers-cleaners' 'Prof-specialty'
 'Other-service' 'Sales' 'Craft-repair' 'Transport-moving'
 'Farming-fishing' 'Machine-op-inspct' 'Tech-support' '?'
 'Protective-serv' 'Armed-Forces' 'Priv-house-serv']
['Not-in-family' 'Husband' 'Wif

In [9]:
adult_data = adult_data[adult_data['workclass'] != "?"].copy()

In [10]:
adult_data = adult_data[adult_data['occupation'] != "?"].copy()

In [11]:
for col in adult_data:
    print(adult_data[col].unique())

[39 50 38 53 28 37 49 52 31 42 30 23 32 40 34 25 43 54 35 59 56 19 20 45
 22 48 21 24 57 44 41 29 18 47 46 36 79 27 33 76 55 61 70 64 71 66 51 58
 26 17 60 90 75 65 77 62 63 67 74 72 69 68 73 81 78 88 80 84 83 85 82 86]
['State-gov' 'Self-emp-not-inc' 'Private' 'Federal-gov' 'Local-gov'
 'Self-emp-inc' 'Without-pay']
[ 77516  83311 215646 ...  84661 257302 201490]
['Bachelors' 'HS-grad' '11th' 'Masters' '9th' 'Some-college' 'Assoc-acdm'
 'Assoc-voc' '7th-8th' 'Doctorate' 'Prof-school' '5th-6th' '10th'
 'Preschool' '12th' '1st-4th']
[13  9  7 14  5 10 12 11  4 16 15  3  6  1  8  2]
['Never-married' 'Married-civ-spouse' 'Divorced' 'Married-spouse-absent'
 'Separated' 'Married-AF-spouse' 'Widowed']
['Adm-clerical' 'Exec-managerial' 'Handlers-cleaners' 'Prof-specialty'
 'Other-service' 'Sales' 'Craft-repair' 'Transport-moving'
 'Farming-fishing' 'Machine-op-inspct' 'Tech-support' 'Protective-serv'
 'Armed-Forces' 'Priv-house-serv']
['Not-in-family' 'Husband' 'Wife' 'Own-child' 'Unmarried' 

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDRegressor
import math

In [13]:
adult_data.drop_duplicates()

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income  
0              2174             0              40  United-States  <=50K  
1                 0             0              13  United-States  <=50K  
2                 0             0              40  United-States  <=50K  
3                 0             0              40  United-States  <=50K  
4                 0             0              40           Cuba  <=50K  
...             ...           ...             ...            ...    ...  
32556             0             0              38  United-States  <=50K  
32557             0             0              40  United-States   >50K  
32558             0             0              40  United-States  <=50K  
32559             0             0              20  United-States  <=50K  
32560         15024             0              40  United-States   >50K  

[30694 rows x 15 columns]

In [14]:
adult_data.describe()

age        fnlwgt  education-num  capital-gain  capital-loss  \
count  30718.000000  3.071800e+04   30718.000000  30718.000000  30718.000000   
mean      38.443584  1.898455e+05      10.130314   1106.037079     88.910216   
std       13.118227  1.054583e+05       2.562469   7497.863364    405.657203   
min       17.000000  1.376900e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178285e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.785170e+05      10.000000      0.000000      0.000000   
75%       47.000000  2.373170e+05      13.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours-per-week  
count    30718.000000  
mean        40.949313  
std         11.985382  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [15]:
adult_data = adult_data.drop(columns=['education'])


In [16]:
adult_data

age         workclass  fnlwgt  education-num      marital-status  \
0       39         State-gov   77516             13       Never-married   
1       50  Self-emp-not-inc   83311             13  Married-civ-spouse   
2       38           Private  215646              9            Divorced   
3       53           Private  234721              7  Married-civ-spouse   
4       28           Private  338409             13  Married-civ-spouse   
...    ...               ...     ...            ...                 ...   
32556   27           Private  257302             12  Married-civ-spouse   
32557   40           Private  154374              9  Married-civ-spouse   
32558   58           Private  151910              9             Widowed   
32559   22           Private  201490              9       Never-married   
32560   52      Self-emp-inc  287927              9  Married-civ-spouse   

              occupation   relationship   race     sex  capital-gain  \
0           Adm-clerical  Not-in-family  White    Male          2174   
1        Exec-managerial        Husband  White    Male             0   
2      Handlers-cleaners  Not-in-family  White    Male             0   
3      Handlers-cleaners        Husband  Black    Male             0   
4         Prof-specialty           Wife  Black  Female             0   
...                  ...            ...    ...     ...           ...   
32556       Tech-support           Wife  White  Female             0   
32557  Machine-op-inspct        Husband  White    Male             0   
32558       Adm-clerical      Unmarried  White  Female             0   
32559       Adm-clerical      Own-child  White    Male             0   
32560    Exec-managerial           Wife  White  Female         15024   

       capital-loss  hours-per-week native-country income  
0                 0              40  United-States  <=50K  
1                 0              13  United-States  <=50K  
2                 0              40  United-States  <=50K  
3                 0              40  United-States  <=50K  
4                 0              40           Cuba  <=50K  
...             ...             ...            ...    ...  
32556             0              38  United-States  <=50K  
32557             0              40  United-States   >50K  
32558             0              40  United-States  <=50K  
32559             0              20  United-States  <=50K  
32560             0              40  United-States   >50K  

[30718 rows x 14 columns]

In [17]:
import scipy.stats as stats

In [18]:
adult_data["age"] = stats.zscore(adult_data.age)

In [19]:
adult_data["fnlwgt"] = stats.zscore(adult_data.fnlwgt)

In [20]:
adult_data["education-num"] = stats.zscore(adult_data["education-num"])
adult_data["capital-gain"] = stats.zscore(adult_data["capital-gain"])


In [21]:
adult_data["capital-loss"] = stats.zscore(adult_data["capital-loss"])

In [22]:
adult_data.head()

age         workclass    fnlwgt  education-num      marital-status  \
0  0.042416         State-gov -1.065173       1.119909       Never-married   
1  0.880958  Self-emp-not-inc -1.010222       1.119909  Married-civ-spouse   
2 -0.033815           Private  0.244655      -0.441111            Divorced   
3  1.109651           Private  0.425535      -1.221621  Married-civ-spouse   
4 -0.796125           Private  1.408764       1.119909  Married-civ-spouse   

          occupation   relationship   race     sex  capital-gain  \
0       Adm-clerical  Not-in-family  White    Male      0.142438   
1    Exec-managerial        Husband  White    Male     -0.147516   
2  Handlers-cleaners  Not-in-family  White    Male     -0.147516   
3  Handlers-cleaners        Husband  Black    Male     -0.147516   
4     Prof-specialty           Wife  Black  Female     -0.147516   

   capital-loss  hours-per-week native-country income  
0     -0.219179              40  United-States  <=50K  
1     -0.219179              13  United-States  <=50K  
2     -0.219179              40  United-States  <=50K  
3     -0.219179              40  United-States  <=50K  
4     -0.219179              40           Cuba  <=50K

In [23]:
adult_data.income.unique()

array(['<=50K', '>50K'], dtype=object)

In [24]:
adult_data.income.value_counts()

income
<=50K    23068
>50K      7650
Name: count, dtype: int64

In [25]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [26]:
le = LabelEncoder

In [27]:
adult_data['income_label'] = le().fit_transform(adult_data['income'])

In [28]:
adult_data.income_label.value_counts()

income_label
0    23068
1     7650
Name: count, dtype: int64

In [ ]:
ohearray = OneHotEncoder.fit_transform